name: CI

on:
  push:
    branches:
      - 'main'
      - '001-*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint (if configured)
        run: |
          if [ -f package.json ] && cat package.json | grep -q 'eslint'; then npm run lint || true; else echo "No eslint configured"; fi

      - name: Run unit tests
        run: |
          npm run test:unit -- --runInBand

      - name: Run contract tests
        run: |
          npm run test:contract -- --runInBand

      - name: Upload test results (Jest)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: |
            ./jest-results.json
